# Form implementation generated from reading ui file 'ChromaWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(387, 235)
        Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);\n"
"")
        self.minClipFilter = QtWidgets.QPushButton(Dialog)
        self.minClipFilter.setGeometry(QtCore.QRect(30, 150, 141, 23))
        self.minClipFilter.setStyleSheet("QPushButton {color:rgb(0, 0, 0);} \n"
"QPushButton {color: rgb(120, 10, 10); background:rgb(210, 210, 210);} \n"
"QPushButton:checked{color: rgb(20, 140, 50); background:rgb(50, 50, 50);}\n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160); border-style: None;}")
        self.minClipFilter.setCheckable(True)
        self.minClipFilter.setObjectName("minClipFilter")
        self.mSmoothingFilter = QtWidgets.QPushButton(Dialog)
        self.mSmoothingFilter.setGeometry(QtCore.QRect(30, 120, 141, 23))
        self.mSmoothingFilter.setStyleSheet("QPushButton {color:rgb(0, 0, 0);} \n"
"QPushButton {color: rgb(120, 10, 10); background:rgb(210, 210, 210);} \n"
"QPushButton:checked{color: rgb(20, 140, 50); background:rgb(50, 50, 50);}\n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160); border-style: None;}")
        self.mSmoothingFilter.setCheckable(True)
        self.mSmoothingFilter.setObjectName("mSmoothingFilter")
        self.nnFilter = QtWidgets.QPushButton(Dialog)
        self.nnFilter.setGeometry(QtCore.QRect(30, 90, 141, 23))
        self.nnFilter.setStyleSheet("QPushButton {color:rgb(0, 0, 0);} \n"
"QPushButton {color: rgb(120, 10, 10); background:rgb(210, 210, 210);} \n"
"QPushButton:checked{color: rgb(20, 140, 50); background:rgb(50, 50, 50);}\n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160); border-style: None;}")
        self.nnFilter.setCheckable(True)
        self.nnFilter.setObjectName("nnFilter")
        self.absoluteFilter = QtWidgets.QPushButton(Dialog)
        self.absoluteFilter.setGeometry(QtCore.QRect(30, 60, 141, 23))
        self.absoluteFilter.setStyleSheet("QPushButton {color:rgb(0, 0, 0);} \n"
"QPushButton {color: rgb(120, 10, 10); background:rgb(210, 210, 210);} \n"
"QPushButton:checked{color: rgb(20, 140, 50); background:rgb(50, 50, 50);}\n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160); border-style: None;}")
        self.absoluteFilter.setCheckable(True)
        self.absoluteFilter.setObjectName("absoluteFilter")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 20))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.minClipValue = QtWidgets.QDoubleSpinBox(Dialog)
        self.minClipValue.setGeometry(QtCore.QRect(180, 150, 62, 22))
        self.minClipValue.setMinimum(0.01)
        self.minClipValue.setMaximum(90.0)
        self.minClipValue.setSingleStep(0.01)
        self.minClipValue.setObjectName("minClipValue")
        self.convertMidi = QtWidgets.QPushButton(Dialog)
        self.convertMidi.setGeometry(QtCore.QRect(250, 190, 121, 31))
        self.convertMidi.setStyleSheet("QPushButton {color: rgb(0, 0, 0); background-color: rgb(210, 210, 210);} \n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160);}\n"
"")
        self.convertMidi.setObjectName("convertMidi")
        self.updateChroma = QtWidgets.QPushButton(Dialog)
        self.updateChroma.setGeometry(QtCore.QRect(130, 190, 121, 31))
        self.updateChroma.setStyleSheet("QPushButton {color: rgb(0, 0, 0); background-color: rgb(210, 210, 210);} \n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160);}\n"
"")
        self.updateChroma.setObjectName("updateChroma")
        self.showChroma = QtWidgets.QPushButton(Dialog)
        self.showChroma.setGeometry(QtCore.QRect(10, 190, 121, 31))
        self.showChroma.setStyleSheet("QPushButton {color: rgb(0, 0, 0); background-color: rgb(210, 210, 210);} \n"
"QPushButton:disabled{color: rgb(70, 70, 70);background-color: rgb(160, 160, 160);}\n"
"")
        self.showChroma.setObjectName("showChroma")
        self.mSmoothingValue = QtWidgets.QDoubleSpinBox(Dialog)
        self.mSmoothingValue.setGeometry(QtCore.QRect(180, 120, 62, 22))
        self.mSmoothingValue.setDecimals(0)
        self.mSmoothingValue.setMinimum(1.0)
        self.mSmoothingValue.setMaximum(100.0)
        self.mSmoothingValue.setSingleStep(1.0)
        self.mSmoothingValue.setProperty("value", 8.0)
        self.mSmoothingValue.setObjectName("mSmoothingValue")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.minClipFilter.setText(_translate("Dialog", "Miniumum Clip"))
        self.mSmoothingFilter.setText(_translate("Dialog", "Median Smoothing"))
        self.nnFilter.setText(_translate("Dialog", "Nearest-Neighbour"))
        self.absoluteFilter.setText(_translate("Dialog", "Absolute"))
        self.label.setText(_translate("Dialog", "Filters"))
        self.convertMidi.setText(_translate("Dialog", "Convert to MIDI"))
        self.updateChroma.setText(_translate("Dialog", "Update Chromagram"))
        self.showChroma.setText(_translate("Dialog", "Show Chromagram"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
