# Form implementation generated from reading ui file 'realtime-chroma-ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1081, 459)
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);\n"
"")
        self.graphicsChroma = QtWidgets.QGraphicsView(Form)
        self.graphicsChroma.setGeometry(QtCore.QRect(230, 70, 601, 361))
        self.graphicsChroma.setStyleSheet("QGraphicsView {\n"
"border-style: inset;\n"
"} \n"
"\n"
"")
        self.graphicsChroma.setObjectName("graphicsChroma")
        self.absoluteFilter = QtWidgets.QPushButton(Form)
        self.absoluteFilter.setGeometry(QtCore.QRect(10, 70, 131, 23))
        self.absoluteFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.absoluteFilter.setCheckable(True)
        self.absoluteFilter.setObjectName("absoluteFilter")
        self.mSmoothingFilter = QtWidgets.QPushButton(Form)
        self.mSmoothingFilter.setGeometry(QtCore.QRect(10, 130, 131, 23))
        self.mSmoothingFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.mSmoothingFilter.setCheckable(True)
        self.mSmoothingFilter.setObjectName("mSmoothingFilter")
        self.minClipFilter = QtWidgets.QPushButton(Form)
        self.minClipFilter.setEnabled(True)
        self.minClipFilter.setGeometry(QtCore.QRect(10, 160, 131, 23))
        self.minClipFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.minClipFilter.setCheckable(True)
        self.minClipFilter.setChecked(False)
        self.minClipFilter.setObjectName("minClipFilter")
        self.nnFilter = QtWidgets.QPushButton(Form)
        self.nnFilter.setGeometry(QtCore.QRect(10, 102, 131, 21))
        self.nnFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.nnFilter.setCheckable(True)
        self.nnFilter.setObjectName("nnFilter")
        self.minClipValue = QtWidgets.QDoubleSpinBox(Form)
        self.minClipValue.setGeometry(QtCore.QRect(150, 160, 51, 22))
        self.minClipValue.setStyleSheet("QDoubleSpinBox {\n"
"color: rgb(230, 230, 230); \n"
"background:rgb(50, 50, 50); \n"
"}")
        self.minClipValue.setMinimum(0.01)
        self.minClipValue.setMaximum(90.0)
        self.minClipValue.setSingleStep(0.01)
        self.minClipValue.setObjectName("minClipValue")
        self.mSmoothingValue = QtWidgets.QDoubleSpinBox(Form)
        self.mSmoothingValue.setGeometry(QtCore.QRect(150, 130, 51, 22))
        self.mSmoothingValue.setStyleSheet("QDoubleSpinBox {\n"
"color: rgb(230, 230, 230); \n"
"background:rgb(50, 50, 50); \n"
"}")
        self.mSmoothingValue.setDecimals(0)
        self.mSmoothingValue.setMinimum(1.0)
        self.mSmoothingValue.setMaximum(100.0)
        self.mSmoothingValue.setSingleStep(1.0)
        self.mSmoothingValue.setProperty("value", 8.0)
        self.mSmoothingValue.setObjectName("mSmoothingValue")
        self.applySettings = QtWidgets.QPushButton(Form)
        self.applySettings.setEnabled(True)
        self.applySettings.setGeometry(QtCore.QRect(10, 380, 201, 51))
        self.applySettings.setStyleSheet("QPushButton {\n"
"color: rgb(0, 0, 0);\n"
" background:rgb(210, 210, 210);\n"
"} \n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160);\n"
"border-style: None;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.applySettings.setCheckable(False)
        self.applySettings.setChecked(False)
        self.applySettings.setObjectName("applySettings")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 360, 221, 20))
        self.line.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 430, 841, 20))
        self.line_5.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_5.setMidLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setObjectName("line_5")
        self.ChromaAlgorithmsLabel = QtWidgets.QLabel(Form)
        self.ChromaAlgorithmsLabel.setGeometry(QtCore.QRect(0, 20, 221, 40))
        self.ChromaAlgorithmsLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.ChromaAlgorithmsLabel.setScaledContents(False)
        self.ChromaAlgorithmsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ChromaAlgorithmsLabel.setObjectName("ChromaAlgorithmsLabel")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(0, 50, 841, 20))
        self.line_6.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_6.setMidLineWidth(1)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(0, 10, 841, 20))
        self.line_7.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_7.setMidLineWidth(1)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setObjectName("line_7")
        self.keyLabel = QtWidgets.QLabel(Form)
        self.keyLabel.setGeometry(QtCore.QRect(250, 20, 41, 40))
        self.keyLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 40, 40);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.keyLabel.setScaledContents(False)
        self.keyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.keyLabel.setObjectName("keyLabel")
        self.keyResLabel = QtWidgets.QLabel(Form)
        self.keyResLabel.setGeometry(QtCore.QRect(290, 20, 61, 40))
        self.keyResLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(20, 20, 20);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.keyResLabel.setText("")
        self.keyResLabel.setScaledContents(False)
        self.keyResLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.keyResLabel.setObjectName("keyResLabel")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(520, 20, 20, 41))
        self.line_9.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_9.setLineWidth(5)
        self.line_9.setMidLineWidth(5)
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_9.setObjectName("line_9")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(280, 20, 20, 41))
        self.line_11.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_11.setLineWidth(1)
        self.line_11.setMidLineWidth(1)
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_11.setObjectName("line_11")
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(640, 20, 20, 41))
        self.line_15.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_15.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_15.setLineWidth(1)
        self.line_15.setMidLineWidth(1)
        self.line_15.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Form)
        self.line_16.setGeometry(QtCore.QRect(720, 20, 20, 41))
        self.line_16.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_16.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_16.setLineWidth(1)
        self.line_16.setMidLineWidth(1)
        self.line_16.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_16.setObjectName("line_16")
        self.bpmLabel = QtWidgets.QLabel(Form)
        self.bpmLabel.setGeometry(QtCore.QRect(610, 20, 41, 40))
        self.bpmLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 40, 40);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.bpmLabel.setScaledContents(False)
        self.bpmLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bpmLabel.setObjectName("bpmLabel")
        self.bpmBackLabel = QtWidgets.QLabel(Form)
        self.bpmBackLabel.setGeometry(QtCore.QRect(650, 20, 81, 40))
        self.bpmBackLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(20, 20, 20);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.bpmBackLabel.setText("")
        self.bpmBackLabel.setScaledContents(False)
        self.bpmBackLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bpmBackLabel.setObjectName("bpmBackLabel")
        self.bpmLCD = QtWidgets.QLCDNumber(Form)
        self.bpmLCD.setGeometry(QtCore.QRect(660, 30, 64, 21))
        self.bpmLCD.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.bpmLCD.setObjectName("bpmLCD")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setGeometry(QtCore.QRect(210, 20, 20, 421))
        self.line_10.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_10.setLineWidth(3)
        self.line_10.setMidLineWidth(3)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_10.setObjectName("line_10")
        self.audioAlgorithmsLabel = QtWidgets.QLabel(Form)
        self.audioAlgorithmsLabel.setGeometry(QtCore.QRect(0, 210, 221, 40))
        self.audioAlgorithmsLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.audioAlgorithmsLabel.setScaledContents(False)
        self.audioAlgorithmsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.audioAlgorithmsLabel.setObjectName("audioAlgorithmsLabel")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(0, 200, 221, 20))
        self.line_8.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_8.setMidLineWidth(1)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setObjectName("line_8")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(0, 240, 221, 20))
        self.line_12.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_12.setMidLineWidth(1)
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_12.setObjectName("line_12")
        self.instrumentFilter = QtWidgets.QPushButton(Form)
        self.instrumentFilter.setEnabled(True)
        self.instrumentFilter.setGeometry(QtCore.QRect(10, 320, 131, 23))
        self.instrumentFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.instrumentFilter.setCheckable(True)
        self.instrumentFilter.setChecked(False)
        self.instrumentFilter.setObjectName("instrumentFilter")
        self.lowPassFilter = QtWidgets.QPushButton(Form)
        self.lowPassFilter.setGeometry(QtCore.QRect(10, 290, 131, 23))
        self.lowPassFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.lowPassFilter.setCheckable(True)
        self.lowPassFilter.setObjectName("lowPassFilter")
        self.highPassFilter = QtWidgets.QPushButton(Form)
        self.highPassFilter.setGeometry(QtCore.QRect(10, 260, 131, 23))
        self.highPassFilter.setStyleSheet("QPushButton {\n"
"color:rgb(0, 0, 0);\n"
"} \n"
"\n"
"QPushButton {\n"
"color: rgb(140, 50, 50);\n"
"background:rgb(200, 200, 200);\n"
"} \n"
"\n"
"QPushButton:checked{\n"
"color: rgb(20, 180, 70); \n"
"background:rgb(60, 60, 60);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(70, 70, 70);\n"
"background-color: rgb(160, 160, 160); \n"
"border-style: None;\n"
"}")
        self.highPassFilter.setCheckable(True)
        self.highPassFilter.setObjectName("highPassFilter")
        self.line_13 = QtWidgets.QFrame(Form)
        self.line_13.setGeometry(QtCore.QRect(830, 20, 20, 421))
        self.line_13.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_13.setLineWidth(3)
        self.line_13.setMidLineWidth(3)
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_13.setObjectName("line_13")
        self.line_17 = QtWidgets.QFrame(Form)
        self.line_17.setGeometry(QtCore.QRect(240, 20, 20, 41))
        self.line_17.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_17.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_17.setLineWidth(1)
        self.line_17.setMidLineWidth(1)
        self.line_17.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_17.setObjectName("line_17")
        self.probabilityLabel = QtWidgets.QLabel(Form)
        self.probabilityLabel.setGeometry(QtCore.QRect(350, 20, 81, 40))
        self.probabilityLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 40, 40);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.probabilityLabel.setScaledContents(False)
        self.probabilityLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.probabilityLabel.setObjectName("probabilityLabel")
        self.probabilityLCD = QtWidgets.QLCDNumber(Form)
        self.probabilityLCD.setGeometry(QtCore.QRect(440, 30, 51, 21))
        self.probabilityLCD.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.probabilityLCD.setObjectName("probabilityLCD")
        self.bpmBackLabel_2 = QtWidgets.QLabel(Form)
        self.bpmBackLabel_2.setGeometry(QtCore.QRect(430, 20, 71, 40))
        self.bpmBackLabel_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(20, 20, 20);\n"
"border-color: rgb(160, 160, 160);\n"
"")
        self.bpmBackLabel_2.setText("")
        self.bpmBackLabel_2.setScaledContents(False)
        self.bpmBackLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bpmBackLabel_2.setObjectName("bpmBackLabel_2")
        self.line_18 = QtWidgets.QFrame(Form)
        self.line_18.setGeometry(QtCore.QRect(600, 20, 20, 41))
        self.line_18.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_18.setLineWidth(1)
        self.line_18.setMidLineWidth(1)
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(Form)
        self.line_19.setGeometry(QtCore.QRect(340, 20, 20, 41))
        self.line_19.setStyleSheet("color: rgb(170, 170, 170);\n"
"background-color: None;")
        self.line_19.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_19.setLineWidth(1)
        self.line_19.setMidLineWidth(1)
        self.line_19.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_19.setObjectName("line_19")
        self.bpmBackLabel_2.raise_()
        self.probabilityLabel.raise_()
        self.audioAlgorithmsLabel.raise_()
        self.keyResLabel.raise_()
        self.keyLabel.raise_()
        self.bpmLabel.raise_()
        self.bpmBackLabel.raise_()
        self.ChromaAlgorithmsLabel.raise_()
        self.graphicsChroma.raise_()
        self.absoluteFilter.raise_()
        self.mSmoothingFilter.raise_()
        self.minClipFilter.raise_()
        self.nnFilter.raise_()
        self.minClipValue.raise_()
        self.mSmoothingValue.raise_()
        self.applySettings.raise_()
        self.line.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_9.raise_()
        self.line_11.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.bpmLCD.raise_()
        self.line_10.raise_()
        self.line_8.raise_()
        self.line_12.raise_()
        self.instrumentFilter.raise_()
        self.lowPassFilter.raise_()
        self.highPassFilter.raise_()
        self.line_13.raise_()
        self.line_17.raise_()
        self.probabilityLCD.raise_()
        self.line_18.raise_()
        self.line_19.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.absoluteFilter.setText(_translate("Form", "Absolute"))
        self.mSmoothingFilter.setText(_translate("Form", "Median Smoothing"))
        self.minClipFilter.setText(_translate("Form", "Miniumum Clip"))
        self.nnFilter.setText(_translate("Form", "Nearest-Neighbour"))
        self.applySettings.setText(_translate("Form", "Apply Settings"))
        self.ChromaAlgorithmsLabel.setText(_translate("Form", "Chroma Filtering Algorithms"))
        self.keyLabel.setText(_translate("Form", "Key"))
        self.bpmLabel.setText(_translate("Form", "BPM"))
        self.audioAlgorithmsLabel.setText(_translate("Form", "Audio Filtering Algorithms"))
        self.instrumentFilter.setText(_translate("Form", "Instrument Filter"))
        self.lowPassFilter.setText(_translate("Form", "Low Pass Filter"))
        self.highPassFilter.setText(_translate("Form", "High Pass Filter"))
        self.probabilityLabel.setText(_translate("Form", "Probability%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
